config/routes.rb
EpiPic::Application.routes.draw do
  resources :users
  resources :sessions
  resources :pictures
  resources :tags
  root :to => 'sessions#new'

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :user
  has_many :tags
  has_many :users, :through => :tags

  has_attached_file :photo, :styles => { :thumb => ["32x32#", :jpg], :medium => ["300x300#", :jpg] }

  validates_attachment :photo, :presence => true,
    :content_type => { :content_type =>  /\Aimage\/.*\Z/ },
    :size => { :in => 0..5000.kilobytes }

  def find_next(current_user)
    current_picture = current_user.pictures.index(self)
    next_picture = current_user.pictures[current_picture + 1]
    if next_picture == nil
      next_picture = current_user.pictures[0]
    end
  next_picture
  end

  def find_previous(current_user)
    current_picture = current_user.pictures.index(self)
    previous_picture = current_user.pictures[current_picture - 1]
    if previous_picture == nil
      previous_picture = current_user.pictures.last
    end
  previous_picture
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :user
  belongs_to :picture
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :pictures
  has_many :tags

  has_many :tagged_pictures, :through => :tags, :source => :picture

  validates_uniqueness_of :user_name
  validates_presence_of :name
  validates_presence_of :user_name


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to sessions_path, alert: "You need to be logged in to do that" if current_user.nil?
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_filter :authorize, only: [:create, :destroy]
  def index
    if current_user == nil
      redirect_to root_url, notice: "Please sign in"
    else
      render 'index'
    end
  end

  def create
    @picture = Picture.new(picture_params)
    if @picture.save
      redirect_to pictures_path, notice: "Upload Successful!"
    else
      render 'new'
    end
  end

  def new
    @picture = Picture.new
    if current_user == nil
      redirect_to root_url, notice: "Please sign in"
    end
  end

  def show
    @tag = Tag.new
    @picture = Picture.find(params[:id])
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.delete
    redirect_to("/pictures")
  end

private

  def picture_params
    params.require(:picture).permit(:photo, :caption, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_user_name(params[:user_name])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to pictures_path
      else
        flash.now.alert = "User name or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def new
    @tag = Tag.new
  end

  def create
    picture = params[:tag][:picture_id]
    current_tags = Tag.where(:picture_id => picture)
    current_tags.each do |i|
      i.destroy
    end
    @tag = Tag.new(tag_params)
    params[:tag][:user_ids].each do |user_id|
      if user_id != ""
        @tag = Tag.create(:user_id => user_id, :picture_id => params[:tag][:picture_id])
      end
    end
    redirect_to picture_path(params[:tag][:picture_id])
  end

private

  def tag_params
    params.require(:tag).permit(:user_id, :picture_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to pictures_path, notice: "Thank you for signing up!"
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    if @user == nil
      redirect_to root_url, notice: "Please sign in"
    else
      render 'show'
    end
  end

private
  def user_params
    params.require(:user).permit(:user_name, :name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EpiPic</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="the_flash">
  <%= flash[:alert] %>
  <%= flash[:notice] %>
    </div>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">

    <div class="navbar-header">
 <br />

  <% if current_user %>
  Logged in as <%= current_user.user_name %>
  &nbsp;
  &nbsp;
  <%= link_to "Log Out", session_path('current'), method: "delete" %>
  <% end %>
  &nbsp;
  &nbsp;
  <%= link_to "Login", new_session_path %>

  &nbsp;
  &nbsp;
  &nbsp;
  <%= link_to "New User", new_user_path %>

  </div>
</div>
</nav>

<%= yield %>

</div>

</body>
</html>

app/views/pictures/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
  <div class="container-fluid">

    <div class="navbar-footer">
 <br />

  &nbsp;
  &nbsp;
  <%= link_to "View My Library", pictures_path %>
  &nbsp;
  &nbsp;
  <%= link_to "View My People", users_path %>
  &nbsp;
  &nbsp;
  <%= link_to "Upload Photo", new_picture_path %>
   &nbsp;
  &nbsp;
  <% if current_user != nil %>
    <%= link_to "View Profile", user_path(current_user) %>
  <% end %>


  </div>
</div>
</nav>

app/views/pictures/index.html.erb
<h1> Epicodus Year Book </h1>

<h3> Spring 2014 </h3>
<div class="well">
<ul class="list-unstyled">


<% current_user.pictures.each do |picture| %>

<li class="photos"><%= link_to image_tag(picture.photo.url(:medium)), picture_path(picture) %></li>




<% end %>
</ul>

</div>

<%= render("nav") %>

app/views/pictures/new.html.erb
<h1>Upload a new picture!</h1>
<br />
<br />


<%= form_for @picture, :url => pictures_path, :html => { :multipart => true } do |form| %>
  <%= form.label :photo, "Click the button to choose a picture to upload:" %>
  <%= form.file_field :photo %>

  <%= form.label :caption, "Enter a caption for your pic:" %>
  <%= form.text_field :caption %>

  <%= form.hidden_field :user_id, :value => session[:user_id] %>
  <%= form.submit(:class => "btn btn-primary") %>
<% end %>

app/views/pictures/show.html.erb
<figure>
<%= image_tag @picture.photo(:medium) %>
<figcaption> <%= @picture.caption %> </figcaption>
</figure>
<jumbotron>

<%= form_for @tag, :url => tags_path, method: :post, :html => { :multipart => true } do |form| %>
<%= hidden_field_tag "tag[picture_id]", @picture.id %>
<%= hidden_field_tag "tag[user_ids][]", nil %>

<% User.all.each do |user| %>
  <%= check_box_tag "tag[user_ids][]", user.id, @picture.users.include?(user) %>
  <%= user.name %><br/>
<% end %>


<%= form.submit(:class => "btn btn-primary") %>
<% end %>



<br />


   <%= link_to "Delete Pic", picture_path(@picture),
                                            :confirm => "You Sure?",
                                            :method => "delete",
                                            :class => "btn btn-danger" %>
</jumbotron>

<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
  <div class="container-fluid">

    <div class="navbar-footer">
 <br />

  &nbsp;
  &nbsp;
  <%= link_to "View My Library", pictures_path %>
  &nbsp;
  &nbsp;
  <%= link_to "Upload Photo", new_picture_path %>
<div class="rightSideNav">
  &nbsp;
  &nbsp;
  <%= link_to "Previous Photo", picture_path(@picture.find_previous(current_user)) %>

  &nbsp;
  &nbsp;

  <%= link_to "Next Photo", picture_path(@picture.find_next(current_user)) %>
</div>

  </div>
</div>
</nav>

app/views/users/index.html.erb
<h1>Select a user to see </h1>

<div class="well">
<ul class="list-unstyled big">

  <% User.all.each do |user| %>
  <li><strong><%= user.user_name %></strong>:&nbsp; <%= user.name %></li>
  <% end %>

</ul>
</div>
<%= render('/pictures/nav') %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br />
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <br />

  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<h4>Your tagged pictures:</h4>

<%= render("pictures/nav") %>

<div class="well">
  <ul class="list-unstyled">
    <% @user.tagged_pictures.each do |pic| %>
      <li><%= image_tag pic.photo(:medium) %></li>
    <% end %>
  </ul>
</div>